#!/usr/bin/env bash
# Generate locked/LOCK-MANIFEST.sha256 for a locked project.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_NAME="${1:-}"

usage() {
  echo "Usage: bash scripts/update-lock-manifest.sh <project-name>"
  echo "Example: bash scripts/update-lock-manifest.sh huanghe-minsu-horror-001"
}

if [ "$PROJECT_NAME" = "-h" ] || [ "$PROJECT_NAME" = "--help" ] || [ -z "$PROJECT_NAME" ]; then
  usage
  if [ -z "$PROJECT_NAME" ]; then exit 1; else exit 0; fi
fi

case "$PROJECT_NAME" in
  */*|*\\*|.*)
    echo "[lock-manifest] Invalid project name: $PROJECT_NAME" >&2
    exit 1
    ;;
esac

PROJECT_DIR="$ROOT_DIR/projects/$PROJECT_NAME"
LOCKED_DIR="$PROJECT_DIR/locked"
FINAL_SCRIPT="$LOCKED_DIR/FINAL-SCRIPT.md"
MANIFEST="$LOCKED_DIR/LOCK-MANIFEST.sha256"

if [ ! -d "$PROJECT_DIR" ]; then
  echo "[lock-manifest] Missing project: projects/$PROJECT_NAME" >&2
  exit 1
fi
if [ ! -f "$FINAL_SCRIPT" ]; then
  echo "[lock-manifest] Missing locked/FINAL-SCRIPT.md for projects/$PROJECT_NAME" >&2
  exit 1
fi

hash_file() {
  local file="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$file" | awk '{print $1}'
  else
    shasum -a 256 "$file" | awk '{print $1}'
  fi
}

{
  echo "# LOCK-MANIFEST.sha256"
  echo "# Generated by scripts/update-lock-manifest.sh"
  echo "# Format: SHA256  relative/path"

  rel="locked/FINAL-SCRIPT.md"
  printf "%s  %s\n" "$(hash_file "$PROJECT_DIR/$rel")" "$rel"

  if [ -d "$PROJECT_DIR/scripts" ]; then
    find "$PROJECT_DIR/scripts" -maxdepth 1 -name "*.md" -not -name "SCRIPT-STATUS.md" -type f -print |
      sort |
      while IFS= read -r script_file; do
        rel="scripts/$(basename "$script_file")"
        printf "%s  %s\n" "$(hash_file "$script_file")" "$rel"
      done
  fi
} > "$MANIFEST"

echo "[lock-manifest] Updated projects/$PROJECT_NAME/locked/LOCK-MANIFEST.sha256"
