#!/usr/bin/env bash
# Generate locked/SKILL-LOCK-MANIFEST.sha256 for the genre Skill locked by a project.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_NAME="${1:-}"

usage() {
  echo "Usage: bash scripts/update-skill-lock-manifest.sh <project-name>"
}

if [ "$PROJECT_NAME" = "-h" ] || [ "$PROJECT_NAME" = "--help" ] || [ -z "$PROJECT_NAME" ]; then
  usage
  if [ -z "$PROJECT_NAME" ]; then exit 1; else exit 0; fi
fi

case "$PROJECT_NAME" in
  */*|*\\*|.*)
    echo "[skill-lock-manifest] Invalid project name: $PROJECT_NAME" >&2
    exit 1
    ;;
esac

PROJECT_DIR="$ROOT_DIR/projects/$PROJECT_NAME"
LOCK_FILE="$PROJECT_DIR/GENRE-SKILL-LOCK.md"
MANIFEST="$PROJECT_DIR/locked/SKILL-LOCK-MANIFEST.sha256"

if [ ! -d "$PROJECT_DIR" ]; then
  echo "[skill-lock-manifest] Missing project: projects/$PROJECT_NAME" >&2
  exit 1
fi
if [ ! -f "$LOCK_FILE" ]; then
  echo "[skill-lock-manifest] Missing GENRE-SKILL-LOCK.md for projects/$PROJECT_NAME" >&2
  exit 1
fi

skill_path="$(grep -m 1 '^- Skill 路径：' "$LOCK_FILE" 2>/dev/null | sed 's/^- Skill 路径：//' | tr -d '\r')"
if [ -z "$skill_path" ]; then
  echo "[skill-lock-manifest] GENRE-SKILL-LOCK.md does not record Skill path." >&2
  exit 1
fi

skill_path="${skill_path%/}"
skill_dir="$ROOT_DIR/$skill_path"
if [ ! -d "$skill_dir" ]; then
  echo "[skill-lock-manifest] Skill path not found: $skill_path" >&2
  exit 1
fi

hash_file() {
  local file="$1"
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$file" | awk '{print $1}'
  else
    shasum -a 256 "$file" | awk '{print $1}'
  fi
}

mkdir -p "$(dirname "$MANIFEST")"

{
  echo "# SKILL-LOCK-MANIFEST.sha256"
  echo "# Generated by scripts/update-skill-lock-manifest.sh"
  echo "# Skill path: $skill_path"
  echo "# Format: SHA256  relative/path"

  find "$skill_dir" -type f \
    ! -path "*/.DS_Store" \
    ! -path "*/Thumbs.db" \
    -print |
    sort |
    while IFS= read -r file; do
      rel="${file#$ROOT_DIR/}"
      printf "%s  %s\n" "$(hash_file "$file")" "$rel"
    done
} > "$MANIFEST"

echo "[skill-lock-manifest] Updated projects/$PROJECT_NAME/locked/SKILL-LOCK-MANIFEST.sha256"
