[CmdletBinding(PositionalBinding = $false)]
param(
    [Parameter(Position = 0)]
    [string]$ProjectName
)

$ErrorActionPreference = "Stop"

function Show-Usage {
    Write-Output "Usage: powershell -ExecutionPolicy Bypass -File scripts/update-skill-lock-manifest.ps1 <project-name>"
}

if ([string]::IsNullOrWhiteSpace($ProjectName) -or $ProjectName -in @("-h", "--help", "/?")) {
    Show-Usage
    exit $(if ([string]::IsNullOrWhiteSpace($ProjectName)) { 1 } else { 0 })
}

if ($ProjectName.Contains("/") -or $ProjectName.Contains("\") -or $ProjectName.StartsWith(".")) {
    Write-Error "[skill-lock-manifest] Invalid project name: $ProjectName"
}

$RootDir = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
$ProjectDir = Join-Path $RootDir "projects\$ProjectName"
$LockFile = Join-Path $ProjectDir "GENRE-SKILL-LOCK.md"
$Manifest = Join-Path $ProjectDir "locked\SKILL-LOCK-MANIFEST.sha256"

if (-not (Test-Path -LiteralPath $ProjectDir -PathType Container)) {
    Write-Error "[skill-lock-manifest] Missing project: projects/$ProjectName"
}
if (-not (Test-Path -LiteralPath $LockFile -PathType Leaf)) {
    Write-Error "[skill-lock-manifest] Missing GENRE-SKILL-LOCK.md for projects/$ProjectName"
}

$SkillPath = $null
Get-Content -LiteralPath $LockFile -Encoding UTF8 | ForEach-Object {
    if ($null -eq $SkillPath -and $_.StartsWith("- Skill ")) {
        if ($_.Contains("genre-skills/")) {
            $Parts = $_ -split "：", 2
            if ($Parts.Count -eq 2) {
                $script:SkillPath = $Parts[1].Trim().TrimEnd("/")
            }
        }
    }
}

if ([string]::IsNullOrWhiteSpace($SkillPath)) {
    Write-Error "[skill-lock-manifest] GENRE-SKILL-LOCK.md does not record Skill path."
}

$SkillDir = Join-Path $RootDir $SkillPath
if (-not (Test-Path -LiteralPath $SkillDir -PathType Container)) {
    Write-Error "[skill-lock-manifest] Skill path not found: $SkillPath"
}

$Lines = New-Object System.Collections.Generic.List[string]
$Lines.Add("# SKILL-LOCK-MANIFEST.sha256")
$Lines.Add("# Generated by scripts/update-skill-lock-manifest.ps1")
$Lines.Add("# Skill path: $SkillPath")
$Lines.Add("# Format: SHA256  relative/path")

Get-ChildItem -LiteralPath $SkillDir -Recurse -File |
    Where-Object { $_.Name -notin @(".DS_Store", "Thumbs.db") } |
    Sort-Object FullName |
    ForEach-Object {
        $RelativePath = $_.FullName.Substring($RootDir.Length + 1).Replace("\", "/")
        $Hash = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
        $Lines.Add("$Hash  $RelativePath")
    }

New-Item -ItemType Directory -Path (Split-Path -Parent $Manifest) -Force | Out-Null
[System.IO.File]::WriteAllLines($Manifest, $Lines, [System.Text.UTF8Encoding]::new($false))
Write-Output "[skill-lock-manifest] Updated projects/$ProjectName/locked/SKILL-LOCK-MANIFEST.sha256"
