param(
    [Parameter(Position = 0)]
    [string]$ProjectName
)

$ErrorActionPreference = "Stop"

function Show-Usage {
    Write-Output "Usage: powershell -ExecutionPolicy Bypass -File scripts/update-lock-manifest.ps1 <project-name>"
    Write-Output "Example: powershell -ExecutionPolicy Bypass -File scripts/update-lock-manifest.ps1 huanghe-minsu-horror-001"
}

if ([string]::IsNullOrWhiteSpace($ProjectName) -or $ProjectName -in @("-h", "--help", "/?")) {
    Show-Usage
    exit $(if ([string]::IsNullOrWhiteSpace($ProjectName)) { 1 } else { 0 })
}

if ($ProjectName.Contains("/") -or $ProjectName.Contains("\") -or $ProjectName.StartsWith(".")) {
    Write-Error "[lock-manifest] Invalid project name: $ProjectName"
}

$RootDir = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
$ProjectDir = Join-Path $RootDir "projects\$ProjectName"
$LockedDir = Join-Path $ProjectDir "locked"
$FinalScript = Join-Path $LockedDir "FINAL-SCRIPT.md"
$Manifest = Join-Path $LockedDir "LOCK-MANIFEST.sha256"

if (-not (Test-Path -LiteralPath $ProjectDir -PathType Container)) {
    Write-Error "[lock-manifest] Missing project: projects/$ProjectName"
}
if (-not (Test-Path -LiteralPath $FinalScript -PathType Leaf)) {
    Write-Error "[lock-manifest] Missing locked/FINAL-SCRIPT.md for projects/$ProjectName"
}

$Files = New-Object System.Collections.Generic.List[string]
$Files.Add("locked/FINAL-SCRIPT.md")

$ScriptsDir = Join-Path $ProjectDir "scripts"
if (Test-Path -LiteralPath $ScriptsDir -PathType Container) {
    Get-ChildItem -LiteralPath $ScriptsDir -File -Filter "*.md" |
        Where-Object { $_.Name -ne "SCRIPT-STATUS.md" } |
        Sort-Object Name |
        ForEach-Object { $Files.Add(("scripts/{0}" -f $_.Name)) }
}

$Lines = New-Object System.Collections.Generic.List[string]
$Lines.Add("# LOCK-MANIFEST.sha256")
$Lines.Add("# Generated by scripts/update-lock-manifest.ps1")
$Lines.Add("# Format: SHA256  relative/path")

foreach ($RelativePath in $Files) {
    $FullPath = Join-Path $ProjectDir $RelativePath
    if (Test-Path -LiteralPath $FullPath -PathType Leaf) {
        $Hash = (Get-FileHash -LiteralPath $FullPath -Algorithm SHA256).Hash.ToLowerInvariant()
        $Lines.Add("$Hash  $RelativePath")
    }
}

[System.IO.File]::WriteAllLines($Manifest, $Lines, [System.Text.UTF8Encoding]::new($false))
Write-Output "[lock-manifest] Updated projects/$ProjectName/locked/LOCK-MANIFEST.sha256"
